### PR TITLE
Add m4 and libgpgme-dev to installed dependencies

### PR DESCRIPTION
**Pull request by sharkwouter**
Those were missing, causing pacman to not build with the things we want, like signed packages.

### CODE REVIEW

**Comment by carstene1ns** [comment]
m4 makes not really sense as we are not building with autotools.
error message?

**Comment by sharkwouter** [comment]
I just tested it and it seems m4 is not required for building pacman. Odd, I have seen an error which asks for m4 somewhere.

**Comment by sharkwouter** [comment]
I tested wrong, the pspdev docker container already has m4 installed as a dependency for something else, which is why my test didn't work out like I expected it to. Pacman needs m4, even when building with meson.

Here is the log:
```
root@c84df19218a4:~/psp-pacman# ./pacman-sudo.sh 
--2020-05-18 00:23:40--  https://sources.archlinux.org/other/pacman/pacman-5.2.1.tar.gz
Resolving sources.archlinux.org (sources.archlinux.org)... 88.198.91.70, 2a01:4f8:160:6087::1
Connecting to sources.archlinux.org (sources.archlinux.org)|88.198.91.70|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3300123 (3.1M) [application/gzip]
Saving to: 'pacman-5.2.1.tar.gz'

pacman-5.2.1.tar.gz 100%[===================>]   3.15M  --.-KB/s    in 0.1s    

2020-05-18 00:23:40 (31.4 MB/s) - 'pacman-5.2.1.tar.gz' saved [3300123/3300123]

Extracting pacman-5.2.1.tar.gz...
patching file meson.build
patching file scripts/meson.build
Collecting meson
  Downloading meson-0.54.2.tar.gz (1.7 MB)
     |████████████████████████████████| 1.7 MB 9.8 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting ninja
  Downloading ninja-1.9.0.post1-py3-none-manylinux1_x86_64.whl (98 kB)
     |████████████████████████████████| 98 kB 12.8 MB/s 
Building wheels for collected packages: meson
  Building wheel for meson (PEP 517) ... done
  Created wheel for meson: filename=meson-0.54.2-py3-none-any.whl size=642032 sha256=1ccc306d6a76c8bdf810ec9d7e2ed68cabd646aac2607c83bcd2df17b45de0ac
  Stored in directory: /root/.cache/pip/wheels/f5/c0/f4/d57dce5dcc37d5573150c7d62ea46dbd7a7194e6c852a86c4b
Successfully built meson
Installing collected packages: meson, ninja
Successfully installed meson-0.54.2 ninja-1.9.0.post1
The Meson build system
Version: 0.54.2
Source dir: /root/psp-pacman/build/pacman-5.2.1
Build dir: /root/psp-pacman/build/pacman-5.2.1/build
Build type: native build
Project name: pacman
Project version: 5.2.1
C compiler for the host machine: cc (gcc 9.3.0 "cc (Ubuntu 9.3.0-10ubuntu2) 9.3.0")
C linker for the host machine: cc ld.bfd 2.34
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program python3 found: YES (/root/psp-pacman/build/pacman-5.2.1/venv/bin/python3)
Program m4 found: NO

meson.build:31:0: ERROR: Program(s) ['m4'] not found or not executable

A full log can be found at /root/psp-pacman/build/pacman-5.2.1/build/meson-logs/meson-log.txt
ERROR: Could not run the pacman script.
```

**Comment by carstene1ns** [comment]
Was looking at git checkout and did not find it.
Good thing is a week after last release, they removed it. So we only need this until next version. :+1:
https://git.archlinux.org/pacman.git/commit/?id=7b73c4a75fbddcfa1bc552fed49c228b9cdaf7b0

**Comment by sharkwouter** [comment]
Oh nice, that's one to remember

**Pull request merged**
